import { useEffect, useState } from "react";
import type { GetServerSideProps } from "next";
import Head from "next/head";
import { Rubik } from "@next/font/google";
import axios from "axios";
import Canvas from "../components/canvas/Canvas";
import AlbumCard from "../components/album/AlbumCard";
import AlbumForm from "../components/album/AlbumForm";

const rubik = Rubik({
  style: "italic",
  weight: "800",
});

interface Album {
  id: Number;
  name: String;
  image: String;
  createdAt: Date;
}

const Home = () => {
  const [albums, setAlbums] = useState<Album[]>();

  useEffect(() => {
    axios
      .get("/api/album")
      .then((res) => {
        setAlbums(res.data);
      })
      .catch((error) => {
        console.log("error", error);
      });
  }, []);

  return (
    <>
      <Head>
        <title>Spotify Glitter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main>
        <div
          className={`fixed top-10 left-[10%] xl:left-[14%] -z-10 text-5xl md:text-6xl lg:text-8xl xl:text-[7rem] 2xl:text-[9rem] ${rubik.className} tracking-wide text-[#D7E9B9] drop-shadow-[0_1px_5px_#FF7B54] cursor-pointer`}
        >
          <h1>Spotify</h1>
          <h1 className="mt-5 indent-10">Glitter</h1>
        </div>
        <div className="mt-[23rem] sm:mt-[25rem] md:mt-[27rem] 2xl:mt-[29rem] z-50 flex flex-col items-center">
          <Canvas>
            <AlbumForm />
            <div className="flex flex-wrap gap-6 justify-center">
              {albums?.map((item: Album, index) => {
                return <AlbumCard item={item} key={index} />;
              })}
            </div>
          </Canvas>
          <div></div>
        </div>
      </main>
    </>
  );
};

export default Home;
